src/Babdelaura/BlogBundle/Entity/Article.php
<?php

namespace Babdelaura\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Article
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Babdelaura\BlogBundle\Repository\ArticleRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Article implements DescriptionEntite
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;


    /**
    * @Gedmo\Slug(fields={"titre"})
    * @ORM\Column(length=128, unique=true)
    */
    private $slug;

    /**
     * @var string
     *
     * @ORM\Column(name="titre", type="string", length=255)
     * @Assert\Length(min=5, minMessage="Le titre doit faire au moins {{ limit }} caractères")
     */
    private $titre;

    /**
     * @var string
     *
     * @ORM\Column(name="contenu", type="text")
     * @Assert\NotBlank(message="Le contenu de l'article ne peut pas être vide")
     */
    private $contenu;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="datePublication", type="datetime")
     * @Assert\DateTime()
     */
    private $datePublication;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateEdition", type="datetime", nullable=true)
     */
    private $dateEdition;

    /**
     * @var boolean
     *
     * @ORM\Column(name="publication", type="boolean")
     */
    private $publication;


    /**
    * @ORM\ManyToOne(targetEntity="Babdelaura\BlogBundle\Entity\Image", inversedBy="articles")
    * @ORM\JoinColumn(nullable=true)
    * @Assert\Valid()
    */
    private $image;

    /**
    * @ORM\ManyToOne(targetEntity="Babdelaura\BlogBundle\Entity\Categorie", cascade={"persist"}, inversedBy="articles")
    *
    */
    private $categorie;

    /**
    * @ORM\ManyToMany(targetEntity="Babdelaura\BlogBundle\Entity\Tag", cascade={"persist"}, inversedBy="articles")
    *
    */
    private $tags;

    /**
    * @ORM\OneToMany(targetEntity="Babdelaura\BlogBundle\Entity\Commentaire", cascade={"persist"}, mappedBy="article")
    */
    private $commentaires;

    private $imageTemp;

    public function __construct(){
        $this->datePublication = new \DateTime;
        $this->publication = false;
        $this->commentaires = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return Article
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }


    /**
     * Set titre
     *
     * @param string $titre
     * @return Article
     */
    public function setTitre($titre)
    {
        $this->titre = $titre;

        return $this;
    }

    /**
     * Get titre
     *
     * @return string
     */
    public function getTitre()
    {
        return $this->titre;
    }

    /**
     * Set contenu
     *
     * @param string $contenu
     * @return Article
     */
    public function setContenu($contenu)
    {
        $this->contenu = $contenu;

        return $this;
    }

    /**
     * Get contenu
     *
     * @return string
     */
    public function getContenu()
    {
        return $this->contenu;
    }

    /**
     * Set datePublication
     *
     * @param \DateTime $datePublication
     * @return Article
     */
    public function setDatePublication($datePublication)
    {
        $this->datePublication = $datePublication;

        return $this;
    }

    /**
     * Get datePublication
     *
     * @return \DateTime
     */
    public function getDatePublication()
    {
        return $this->datePublication;
    }

    /**
     * Set dateEdition
     *
     * @param \DateTime $dateEdition
     * @return Article
     */
    public function setDateEdition($dateEdition)
    {
        $this->dateEdition = $dateEdition;

        return $this;
    }

    /**
     * Get dateEdition
     *
     * @return \DateTime
     */
    public function getDateEdition()
    {
        return $this->dateEdition;
    }

    /**
    * @ORM\PreUpdate
    */
    public function updateDateEdition()
    {
        $this->setDateEdition(new \Datetime());
    }

    /**
     * Set publication
     *
     * @param boolean $publication
     * @return Article
     */
    public function setPublication($publication)
    {
        $this->publication = $publication;

        return $this;
    }

    /**
     * Get publication
     *
     * @return boolean
     */
    public function getPublication()
    {
        return $this->publication;
    }

    /**
     * Set image
     *
     * @param \Babdelaura\BlogBundle\Entity\Image $image
     * @return Article
     */
    public function setImage(\Babdelaura\BlogBundle\Entity\Image $image)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Get image
     *
     * @return \Babdelaura\BlogBundle\Entity\Image
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Add commentaires
     *
     * @param \Babdelaura\BlogBundle\Entity\Commentaire $commentaires
     * @return Article
     */
    public function addCommentaire(\Babdelaura\BlogBundle\Entity\Commentaire $commentaires)
    {
        $this->commentaires[] = $commentaires;
        $commentaires->setArticle($this);
        return $this;
    }

    /**
     * Remove commentaires
     *
     * @param \Babdelaura\BlogBundle\Entity\Commentaire $commentaires
     */
    public function removeCommentaire(\Babdelaura\BlogBundle\Entity\Commentaire $commentaires)
    {
        $this->commentaires->removeElement($commentaires);
    }

    /**
     * Get commentaires
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCommentaires()
    {
        return $this->commentaires;
    }

    public function getRootCommentairesValides()
    {
        $commentaires = array();

        foreach ($this->commentaires as $commentaire) {
            if ($commentaire->getValide() && $commentaire->getParent() == null) {
                $commentaires[] = $commentaire;
            }
        }

        return $commentaires;
    }


    public function getNbCommentaires($valide = null)
    {
        $compteur = 0;
        if($valide === null) {
            $compteur = $this->commentaires->count();
        }
        else {
            foreach ($this->commentaires as $commentaire) {
                if($commentaire->getValide() === $valide) {
                    $compteur++;
                }
            }
        }
        return $compteur;
    }


    // TODO simplifier ça en utilisant la méthode getNbCommentaires()
    public function getNbCommentairesNonValides()
    {
        $compteur = 0;
        foreach ($this->commentaires as $commentaire) {
            if($commentaire->getValide() == false) {
                $compteur++;
            }
        }
        return $compteur;
    }

    public function validerCommentaires()
    {
        foreach ($this->commentaires as $commentaire) {
            if($commentaire->getValide() == false ) {
                $commentaire->setValide(true);
            }
        }
    }

    public function getImageTemp() {
        return $this->imageTemp;
    }

    public function setImageTemp($img) {
        $this->imageTemp = $img;
        return $this;
    }


    public function getType() {
        return 'article';
    }

    public function getPathList() {
        return 'babdelaurablog_admin_listerArticles';
    }

    public function getDescription() {
        return $this->titre;
    }

    public function getPrefixeType() {
        return "l'";
    }

    /**
     * Set categorie
     *
     * @param \Babdelaura\BlogBundle\Entity\Categorie $categorie
     *
     * @return Article
     */
    public function setCategorie(\Babdelaura\BlogBundle\Entity\Categorie $categorie = null)
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * Get categorie
     *
     * @return \Babdelaura\BlogBundle\Entity\Categorie
     */
    public function getCategorie()
    {
        return $this->categorie;
    }

    /**
     * Add tag
     *
     * @param \Babdelaura\BlogBundle\Entity\Tag $tag
     *
     * @return Article
     */
    public function addTag(\Babdelaura\BlogBundle\Entity\Tag $tag)
    {
        $this->tags[] = $tag;
        $tag->addArticle($this);

        return $this;
    }

    /**
     * Remove tag
     *
     * @param \Babdelaura\BlogBundle\Entity\Tag $tag
     */
    public function removeTag(\Babdelaura\BlogBundle\Entity\Tag $tag)
    {
        $this->tags->removeElement($tag);
        $tag->removeArticle(null);
    }

    /**
     * Get tags
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTags()
    {
        return $this->tags;
    }
}

src/Babdelaura/BlogBundle/Entity/Image.php
<?php

namespace Babdelaura\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\HttpFoundation\File\UploadedFile;

use Imagine\Gd\Imagine;
use Imagine\Image\Point;

/**
 * Image
 *
 * @ORM\Table()
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="extension", type="string", length=255)
     */
    private $extension;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255, nullable=true)
     */
    private $alt;

    /**
     * @var integer
     *
     * @ORM\Column(name="width", type="integer")
     */
    private $width;

    /**
     * @var integer
     *
     * @ORM\Column(name="height", type="integer")
     */
    private $height;

    private $file;

    private $tempFilename;

    /**
    * @ORM\OneToMany(targetEntity="Babdelaura\BlogBundle\Entity\Article", mappedBy="image")
    */
    private $articles;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set extension
     *
     * @param string $extension
     * @return Image
     */
    public function setExtension($extension)
    {
        $this->extension = $extension;

        return $this;
    }

    /**
     * Get extension
     *
     * @return string
     */
    public function getExtension()
    {
        return $this->extension;
    }

    /**
     * Set alt
     *
     * @param string $alt
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }

    //Upload d'un fichier lorsqu'il en existe déjà un autre
    public function setFile(UploadedFile $file)
    {
        $this->file = $file;

        // On vérifie si on avait déjà un fichier pour cette entité
        if (null !== $this->extension) {
          // On sauvegarde l'extension du fichier pour le supprimer plus tard
          $this->tempFilename = $this->extension;

          // On réinitialise les valeurs des attributs extension et alt
          $this->extension = null;
          $this->alt = null;
        }
    }

    public function getFile()
    {
        return $this->file;
    }

    /**
    * @ORM\PrePersist()
    * @ORM\PreUpdate()
    */
    public function preUpload()
    {
        // Si jamais il n'y a pas de fichier (champ facultatif)
        if (null === $this->file) {
          return;
        }

        // Le nom du fichier est son id, on doit stocker également son extension
        $this->extension = $this->file->guessExtension();
    }

    /**
    * @ORM\PostPersist()
    * @ORM\PostUpdate()
    */
    public function upload()
    {
    // Si jamais il n'y a pas de fichier (champ facultatif)
        if (null === $this->file) {
          return;
        }

        // Si on avait un ancien fichier, on le supprime
        if (null !== $this->tempFilename) {
          $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
          if (file_exists($oldFile)) {
            unlink($oldFile);
          }
        }

        // On déplace le fichier envoyé dans le répertoire de notre choix
        /*$this->file->move(
          $this->getUploadRootDir(), // Le répertoire de destination
          $this->id.'.'.$this->extension   // Le nom du fichier à créer, ici « id.extension »
        );

        if ($this->watermark) {

        }*/
        $path = $this->getUploadRootDir() . '/' . $this->id . '.' . $this->extension;
        $this->image->save($path, array('jpeg_quality' => 100));
    }

    /**
    * @ORM\PreRemove()
    */
    public function preRemoveUpload()
    {
        // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
        $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->extension;
    }

    /**
    * @ORM\PostRemove()
    */
    public function removeUpload()
    {
        // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
        if (file_exists($this->tempFilename)) {
          // On supprime le fichier
          unlink($this->tempFilename);
        }
    }

    public function getUploadDir()
    {
        // On retourne le chemin relatif vers l'image pour un navigateur
        return 'uploads/img';
    }

    protected function getUploadRootDir()
    {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    public function getWebPath()
    {
        return $this->getUploadDir().'/'.$this->getId().'.'.$this->getExtension();
    }
    /**
     * Constructor
     */
    public function __construct($file, $watermark = false)
    {
        $this->WATERMARK_PATH = dirname(__FILE__) . '/../../../../web/images/watermark.png';
        $this->WATERMARK_OFFSET = 2;
        $this->articles = new \Doctrine\Common\Collections\ArrayCollection();
        $this->watermark = $watermark;

        $this->setFile($file);

        $this->imagine = new Imagine();

        $this->image = $this->imagine->open($this->file->getRealPath());
        $imageSourceSize = $this->image->getSize();

        $this->setWidth($imageSourceSize->getWidth());
        $this->setHeight($imageSourceSize->getHeight());

        if ($watermark) {
            $this->addWatermark();
        }
    }

    public function addWatermark() {
        $watermark = $this->imagine->open($this->WATERMARK_PATH);
        $watermarkSize = $watermark->getSize();
        $bottomRight = new Point($this->getWidth() - $watermarkSize->getWidth() - $this->WATERMARK_OFFSET, $this->getHeight() - $watermarkSize->getHeight() - $this->WATERMARK_OFFSET);

        $this->image->paste($watermark, $bottomRight);
    }

    /**
     * Add articles
     *
     * @param \Babdelaura\BlogBundle\Entity\Article $articles
     * @return Image
     */
    public function addArticle(\Babdelaura\BlogBundle\Entity\Article $articles)
    {
        $this->articles[] = $articles;

        return $this;
    }

    /**
     * Remove articles
     *
     * @param \Babdelaura\BlogBundle\Entity\Article $articles
     */
    public function removeArticle(\Babdelaura\BlogBundle\Entity\Article $articles)
    {
        $this->articles->removeElement($articles);
    }

    /**
     * Get articles
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getArticles()
    {
        return $this->articles;
    }

    /**
     * Set width
     *
     * @param integer $width
     *
     * @return Image
     */
    public function setWidth($width)
    {
        $this->width = $width;

        return $this;
    }

    /**
     * Get width
     *
     * @return integer
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * Set height
     *
     * @param integer $height
     *
     * @return Image
     */
    public function setHeight($height)
    {
        $this->height = $height;

        return $this;
    }

    /**
     * Get height
     *
     * @return integer
     */
    public function getHeight()
    {
        return $this->height;
    }
}

src/Babdelaura/BlogBundle/Resources/views/Article/afficherArticle.html.twig
{% extends "BabdelauraBlogBundle::layout.html.twig" %}

{% set metaDescription = article.contenu | truncate(500,true) | striptags %}

{% block facebookMetas %}
    {% set ogImage = asset(article.image.webPath) %}
    {% set ogTitle = article.titre %}

    {{ parent() }}
    <meta property="article:author" content="https://www.facebook.com/BabDeLaura" />
    <meta property="article:publisher" content="https://www.facebook.com/BabDeLaura" />
{% endblock %}

{% block pageTitle %}{{article.titre}} | {% endblock %}

{% block content %}
    <section class="bab-Section">
        {% include 'BabdelauraBlogBundle:Components/article:entry.html.twig' with {'article': article, 'slideshow': true} only %}
    </section>

    <nav class="bab-Section clearfix">
        {% if urlArticleSuivant is not null %}
        <a class="bab-Button bab-Button--block@small pull-left" href="{{ urlArticleSuivant }}">
            {% include 'BabdelauraBlogBundle:Components:icon.html.twig' with {'name': 'chevronLeft'} only %}
            Article plus récent
        </a>
        {% endif %}

        {% if urlArticlePrecedent is not null %}
        <a class="bab-Button bab-Button--block@small pull-right" href="{{ urlArticlePrecedent }}">
            Article plus ancien
            {% include 'BabdelauraBlogBundle:Components:icon.html.twig' with {'name': 'chevronRight'} only %}
        </a>
        {% endif %}
    </nav>

    <section class="bab-Section">
        <h2 class="bab-Section-title">
            Articles similaires
        </h2>
        <div class="bab-Grid bab-Grid--inlineBlock bab-Grid--smallGutters">
            {% set nbArticles = articlesSimilaires|length %}
            {% for article in articlesSimilaires %}
            <div class="bab-Grid-cell bab-Grid-cell--1-{{ nbArticles }} bab-Grid-cell--1-2@medium bab-Grid-cell--1-1@small">
                {% include 'BabdelauraBlogBundle:Components/article:preview.html.twig' with {'article': article, 'small': true, 'titleElement': 'h3'} only %}
            </div>
            {% endfor %}
        </div>
    </section>

    <section class="bab-Section" id="commentaires">
        <h2 class="bab-Section-title">
            Laisser un commentaire
        </h2>
        <section class="bab-CommentForm-container js-comment-form" data-comment-form-notification="#comment-form-notification">
            {% include 'BabdelauraBlogBundle:Components/comment:form.html.twig' with {'form': form} only %}
        </section>
        <section class="js-comments" data-comments-form=".js-comment-form">
            {% include 'BabdelauraBlogBundle:Components/comment:list.html.twig' with {'comments': article.rootCommentairesValides} only %}
        </section>
    </section>

    <div class="bab-Notification" id="comment-form-notification">
        <button class="bab-Notification-close js-notification-closer" type="button">
            {% include 'BabdelauraBlogBundle:Components:icon.html.twig' with {'name': 'cross'} only %}
        </button>
        <p class="bab-Notification-content js-notification-content"></p>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://www.google.com/recaptcha/api.js" async></script>
{% endblock %}

src/Babdelaura/BlogBundle/Resources/views/Article/grille.html.twig
<ul class="bab-Grid bab-Grid--inlineBlock list-unstyled js-articles-grid">
    {% for article in listeArticles %}
        {% set nbCommentaires = article.getNbCommentaires(true) %}

        {% if admin is defined and admin %}
            {% set articleUrl = path('babdelaurablog_admin_afficherArticle', {'slug': article.slug}) %}
        {% else %}
            {% set articleUrl = path('babdelaurablog_article', {'slug': article.slug, 'annee': article.datePublication|date("Y"), 'mois': article.datePublication|date("m"), 'jour': article.datePublication|date("d")}) %}
        {% endif %}

        <li class="bab-Grid-cell bab-Grid-cell--1-2 bab-Grid-cell--1-1@small">
            <figure class="bab-Article--grid js-articles-grid-item" itemscope itemtype="http://schema.org/BlogPosting">
                <img class="bab-Article-image" src="{{ asset(article.image.webPath) }}" alt="{{article.image.alt}}">
                <figcaption class="bab-Article-infos">
                    <h2 class="bab-Article-title" itemprop="name">
                        <a href="{{ articleUrl }}">{{article.titre|truncate(30,true)}}</a>
                    </h2>

                    <a href="{{ articleUrl }}#commentaires">
                    {{nbCommentaires}}
                    {% if nbCommentaires <= 1 %}
                      commentaire
                    {% else %}
                      commentaires
                    {% endif %}
                    </a>

                    <a class="bab-Button" href="{{ articleUrl }}">
                        Lire l'article
                    </a>
                </figcaption>
            </figure>
        </li>
    {% endfor %}
</ul>

src/Babdelaura/BlogBundle/Resources/views/Article/liste.html.twig
{% extends "BabdelauraBlogBundle::layout.html.twig" %}

{% if title is defined %}
  {% set metaDescription = title %}
{% else %}
  {% set metaDescription = 'Tous les articles' %}
{% endif %}

{% block facebookMetas %}
    {% set ogTitle = metaDescription %}

    {{ parent() }}
{% endblock %}

{% block content %}
<section class="bab-Section">
    {% if title is defined %}
        {% set previewTitleElement = 'h3' %}
        <h2 class="bab-Section-title align-center">
            {{ title }}
        </h2>
    {% endif %}

    {% include 'BabdelauraBlogBundle:Components/article:list.html.twig' with {'articles': articles, 'previewTitleElement': previewTitleElement|default('h2')} only %}

    {% include 'BabdelauraBlogBundle:Components/article:pagination.html.twig' with pagination only %}
    {#{{ knp_pagination_render(articles) }}#}
</section>
{% endblock %}